### ISSUE TITLE
Portfolio not showing up on Github

### ISSUE THREAD

**Issue by ishu3101** [daviddarnes/repo-listing-demo#1]
I have forked https://github.com/tutsplus/repo-listing-demo to https://github.com/ishu3101/repo-listing-demo but my portfolio is not showing up when I visit http://ishu3101.github.io/repo-listing-demo/. I'm just getting **File not found** error message.

**Comment by daviddarnes** [comment]
That's odd, maybe try making a minor change to one of the files to force a Jekyll build?

**Comment by ishu3101** [comment]
Thanks, that did the trick. But why does that happen?

How do you sort the order in which the repository are listed? I would like to sort by the number of stars the repo has?

**Comment by daviddarnes** [comment]
I think it happens because GitHub thinks nothing has changed, as all you've done is create the repo without committing a change. Builds will probably only happen when a commit is made.

Sorting it by star count, hmm, you might have to look into liquid templating to get the answer to that [shopify.github.io/liquid](https://shopify.github.io/liquid/)

**Comment by ishu3101** [comment]
When I try to build the site locally, the stylesheets are not showing up.

**Comment by daviddarnes** [comment]
Do you have Jekyll installed? If not I'd recommend referring to their docs [jekyllrb.com/docs](http://jekyllrb.com/docs)

**Comment by ishu3101** [comment]
Yes, I have it installed.

**Comment by daviddarnes** [comment]
In that case I think it's because the file path is different to the live version. I'm sorry but I can't help you anymore, issues are for bugs and changes not for support questions

**Comment by ishu3101** [comment]
What version of Jekyll do I require to build this project locally. I have an older version of Jekyll (version 0.12), which is probably why it cannot find the css stylesheets.

**Comment by daviddarnes** [comment]
You need at least 3+, all the version information is here https://pages.github.com/versions/

Can you stop asking asking questions that are not related to the issue please? This is not the channel to ask such questions.
