### ISSUE TITLE
Liquid Exception: Liquid error: Cannot sort a null object

### ISSUE THREAD

**Issue by ishu3101** [daviddarnes/repo-listing-demo#2]
When I try to build this project using `jekyll serve'` using jekyll version 3.1.6,  I'm getting this error message.

`Liquid Exception: Liquid error (line 19): Cannot sort a null object. in index.html`

**Comment by daviddarnes** [comment]
Did you install just Jekyll gem or the github-pages gem?

**Comment by ishu3101** [comment]
The Jekyll and the github-pages gem.

**Comment by daviddarnes** [comment]
You'll need the github-pages gem for this to work locally. Please refer to the tutorial http://webdesign.tutsplus.com/tutorials/how-to-create-an-open-source-directory-on-github-pages--cms-26225 and the official documentation http://jekyllrb.com
